import type {
  Article,
  Incident,
  Alert,
  Business,
  Resident,
  GalleryImage,
  Notice,
} from "@/types";

export const articles: Article[] = [
  {
    id: "1",
    title: "Annual Community Clean-Up Day a Resounding Success",
    slug: "annual-community-clean-up-2026",
    excerpt:
      "Residents came together in force for our annual clean-up drive, transforming the enclosure's common areas and green spaces.",
    content: "",
    category: { id: "c1", name: "Community", slug: "community", color: "#2D5A3F" },
    author: {
      id: "a1",
      name: "Sarah Moolman",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      role: "Community Manager",
    },
    coverImage: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&h=600&fit=crop",
    publishedAt: "2026-05-25",
    featured: true,
    tags: ["community", "clean-up", "environment"],
    readTime: 4,
    comments: [],
  },
  {
    id: "2",
    title: "New Security Measures Implemented at Main Gate",
    slug: "new-security-measures-main-gate",
    excerpt:
      "Enhanced access control systems and 24/7 monitoring have been installed at all entry points to improve resident safety.",
    content: "",
    category: { id: "c2", name: "Security", slug: "security", color: "#C9A84C" },
    author: {
      id: "a2",
      name: "James Ndlovu",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      role: "Security Lead",
    },
    coverImage: "https://images.unsplash.com/photo-1558002038-1055e2d89ed5?w=1200&h=600&fit=crop",
    publishedAt: "2026-05-23",
    featured: true,
    tags: ["security", "safety", "access-control"],
    readTime: 3,
    comments: [],
  },
  {
    id: "3",
    title: "Local Heroes: Meet the Du Toit Family",
    slug: "meet-the-du-toit-family",
    excerpt:
      "Get to know the family behind the community's beloved weekend gardening initiative.",
    content: "",
    category: { id: "c1", name: "Community", slug: "community", color: "#2D5A3F" },
    author: {
      id: "a3",
      name: "Emily Chen",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      role: "Editor",
    },
    coverImage: "https://images.unsplash.com/photo-1616048056617-93b94e339509?w=1200&h=600&fit=crop",
    publishedAt: "2026-05-20",
    featured: false,
    tags: ["community", "neighbours", "gardening"],
    readTime: 5,
    comments: [],
  },
  {
    id: "4",
    title: "Load Shedding Schedule Update: May 2026",
    slug: "load-shedding-schedule-may-2026",
    excerpt:
      "Eskom has released the updated load shedding timetable for our area. Here's what you need to know.",
    content: "",
    category: { id: "c3", name: "Utilities", slug: "utilities", color: "#8E8E93" },
    author: {
      id: "a1",
      name: "Sarah Moolman",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      role: "Community Manager",
    },
    coverImage: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&h=600&fit=crop",
    publishedAt: "2026-05-18",
    featured: false,
    tags: ["load-shedding", "utilities", "eskom"],
    readTime: 2,
    comments: [],
  },
];

export const incidents: Incident[] = [
  {
    id: "inc-1",
    type: "security",
    title: "Suspicious Vehicle Reported on Kestrel Avenue",
    description: "A dark sedan was observed circling the block late last night. SAPS notified.",
    status: "investigating",
    reportedAt: "2026-05-26T22:30:00",
    updatedAt: "2026-05-27T08:00:00",
    reportedBy: "Resident",
    location: "Kestrel Avenue",
    priority: "high",
  },
  {
    id: "inc-2",
    type: "maintenance",
    title: "Street Light Outage — Jacana Street",
    description: "Two street lights are not functioning near the Jacana Street entrance.",
    status: "open",
    reportedAt: "2026-05-25T19:15:00",
    updatedAt: "2026-05-25T19:15:00",
    reportedBy: "Resident",
    location: "Jacana Street",
    priority: "medium",
  },
];

export const alerts: Alert[] = [
  {
    id: "alert-1",
    type: "emergency",
    title: "⚠️ Emergency Contact Update",
    message:
      "In case of emergency, dial 10111 for SAPS or 086 00 10111 for City of Joburg Emergency Services. For enclosure security, call 082 555 0199.",
    createdAt: "2026-05-01",
    active: true,
    priority: "critical",
  },
  {
    id: "alert-2",
    type: "warning",
    title: "Water Maintenance Scheduled",
    message:
      "Johannesburg Water will be conducting scheduled maintenance on Plover Street on 30 May from 09:00–15:00. Water supply may be affected.",
    createdAt: "2026-05-26",
    expiresAt: "2026-05-31",
    active: true,
    priority: "medium",
  },
];

export const businesses: Business[] = [
  {
    id: "biz-1",
    name: "Precision Electrical Solutions",
    category: "Electrical",
    description: "Certified electrician serving the Fourways area for over 15 years. 24/7 emergency call-out available.",
    phone: "+27 82 555 0101",
    email: "info@precisionelec.co.za",
    address: "Unit 5, Fourways Business Park",
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&h=400&fit=crop",
    hours: "Mon–Fri 07:00–18:00 · Sat 08:00–14:00",
  },
  {
    id: "biz-2",
    name: "Green Thumb Landscaping",
    category: "Gardening",
    description: "Professional gardening and landscaping services. Monthly maintenance and one-off projects.",
    phone: "+27 72 555 0202",
    email: "info@greenthumb.co.za",
    address: "Servicing all of Fourways",
    rating: 4.9,
    reviewCount: 37,
    featured: true,
    image: "https://images.unsplash.com/photo-1557429287-b2e26467fc2b?w=600&h=400&fit=crop",
    hours: "Mon–Sat 06:00–17:00",
  },
  {
    id: "biz-3",
    name: "Apex Plumbing & Drainage",
    category: "Plumbing",
    description: "Emergency plumbing services. Blocked drains, burst pipes, and installations.",
    phone: "+27 83 555 0303",
    email: "info@apexplumbing.co.za",
    address: "Servicing Sandton & surrounds",
    rating: 4.7,
    reviewCount: 19,
    featured: false,
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&h=400&fit=crop",
    hours: "24/7 Emergency Service",
  },
  {
    id: "biz-4",
    name: "La Dolce Vita Italian Restaurant",
    category: "Restaurants",
    description: "Authentic Italian cuisine in the heart of Fourways. Dine-in, takeaway, and delivery.",
    phone: "+27 11 465 1000",
    email: "info@ladolcevita.co.za",
    address: "Shop 4, Fourways Crossing",
    rating: 4.6,
    reviewCount: 142,
    featured: true,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    hours: "Tue–Sun 11:00–22:00",
  },
];

export const galleryImages: GalleryImage[] = [
  {
    id: "g-1",
    src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    alt: "Community garden",
    caption: "Our beautiful community garden",
    category: "community",
    uploadedAt: "2026-05-01",
    width: 800,
    height: 600,
  },
  {
    id: "g-2",
    src: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=1000&fit=crop",
    alt: "Sunset over the enclosure",
    caption: "Golden hour on Jacana Street",
    category: "lifestyle",
    uploadedAt: "2026-04-28",
    width: 800,
    height: 1000,
  },
  {
    id: "g-3",
    src: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=800&fit=crop",
    alt: "Modern homes",
    caption: "Architecture in the enclosure",
    category: "lifestyle",
    uploadedAt: "2026-04-25",
    width: 800,
    height: 800,
  },
  {
    id: "g-4",
    src: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&h=600&fit=crop",
    alt: "Community event",
    caption: "Clean-up day 2026",
    category: "event",
    uploadedAt: "2026-05-20",
    width: 800,
    height: 600,
  },
  {
    id: "g-5",
    src: "https://images.unsplash.com/photo-1616048056617-93b94e339509?w=800&h=600&fit=crop",
    alt: "Children playing",
    caption: "Weekend fun in the park",
    category: "community",
    uploadedAt: "2026-05-15",
    width: 800,
    height: 600,
  },
  {
    id: "g-6",
    src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=700&fit=crop",
    alt: "Security patrol",
    caption: "24/7 security monitoring",
    category: "security",
    uploadedAt: "2026-05-10",
    width: 800,
    height: 700,
  },
];

export const notices: Notice[] = [
  {
    id: "n-1",
    title: "AGM Notice: 15 June 2026",
    content:
      "The Annual General Meeting for the 3 Ways Enclosure Homeowners Association will take place on 15 June 2026 at 18:00 at the Fourways Community Centre. All residents are encouraged to attend.",
    type: "announcement",
    pinned: true,
    createdAt: "2026-05-20",
    author: "Board of Trustees",
  },
  {
    id: "n-2",
    title: "Temporary Gate Closure: 28 May",
    content:
      "The Kestrel Avenue pedestrian gate will be closed for maintenance on 28 May between 08:00 and 16:00. Please use the main entrance.",
    type: "warning",
    pinned: false,
    createdAt: "2026-05-26",
    expiresAt: "2026-05-29",
    author: "Security Team",
  },
];

export const residents: Resident[] = [
  {
    id: "r-1",
    name: "Johan & Marietjie du Toit",
    unit: "12",
    street: "Plover Street",
    role: "resident",
    bio: "Proud residents since 2019. We run the weekend gardening club — all welcome!",
    joinedAt: "2019-03-01",
    verified: true,
  },
  {
    id: "r-2",
    name: "Thabo Molefe",
    unit: "8",
    street: "Kestrel Avenue",
    role: "trustee",
    bio: "Trustee and community advocate. Passionate about safety and neighbourhood development.",
    joinedAt: "2018-06-15",
    verified: true,
  },
  {
    id: "r-3",
    name: "Sarah Moolman",
    unit: "5",
    street: "Jacana Street",
    role: "admin",
    bio: "Community Manager. Here to help make our enclosure the best place to live in Fourways.",
    joinedAt: "2020-01-10",
    verified: true,
  },
];
